name: Show name

on:
  push:
    branches:
      - main

jobs:
  display-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run bash
      run: bash ./show_name.sh